package AES;

import javax.crypto.*;
import java.lang.reflect.Array;
import java.security.InvalidKeyException;
import java.security.Key;
import java.security.NoSuchAlgorithmException;
import java.util.Arrays;

public class AES {
    public static void main(String[] args) throws NoSuchAlgorithmException, NoSuchPaddingException, InvalidKeyException, BadPaddingException, IllegalBlockSizeException

    {
        //AutoGenerated key from Java
        KeyGenerator generator = KeyGenerator.getInstance("AES");
        SecretKey myAesKey = generator.generateKey();
        //System.out.println(myAesKey);

        //Prints out key in 16 bytes
        byte[] myBytes = myAesKey.getEncoded();
        System.out.println("Generated Key: ");
        System.out.println(Arrays.toString(myBytes));

        //Cipher class for AES
        Cipher aesCipher = Cipher.getInstance("AES");

        //Set Object to Encryption
        aesCipher.init(Cipher.ENCRYPT_MODE,myAesKey);
        //Translate String into byte array
        byte[] myBytes2 = "You can always see me during office hours. No appointment is required.".getBytes();

        //Encrypt the Byte array
        byte[] encryptedBytes = aesCipher.doFinal(myBytes2);

        //Print encrypted Array and Text
        System.out.println();
        System.out.println("Encrypted Array: ");
        System.out.println(Arrays.toString(encryptedBytes));
        System.out.println();
        System.out.println("Encrypted Text: ");
        String s = new String(encryptedBytes);
        System.out.println(s);

        //Decrypt the bytes and reprint message
        aesCipher.init(Cipher.DECRYPT_MODE, myAesKey);
        byte[] decryptedBytes = aesCipher.doFinal(encryptedBytes);
        System.out.println();
        System.out.println("Decrypted Array: ");
        System.out.println(Arrays.toString(decryptedBytes));
        System.out.println();
        System.out.println("Decrypted Text: ");
        String s2 = new String(decryptedBytes);
        System.out.println(s2);





    }
}
